spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: leaf-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.161.140:8848
    sentinel:
      transport:
        dashboard: localhost:8888
dubbo:
  scan:
    base-packages: com.sen.leaf.service.impl
  protocol:
    name: dubbo
    port: -1
  provider:
    loadbalance: roundrobin
  registry:
    address: nacos://192.168.161.140:8848

#logging:
#  level:
#    com.funtl.spring.cloud.alibaba.provider.mapper: debug
#    io.seata.core: debug